"""empty message

Revision ID: 444df9604c27
Revises: 2bb94d40680f
Create Date: 2014-11-22 02:07:41.591116

"""

# revision identifiers, used by Alembic.
revision = '444df9604c27'
down_revision = '2bb94d40680f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
